# Generated by Django 4.0.2 on 2022-12-08 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musictracks',
            old_name='description',
            new_name='lyrics',
        ),
        migrations.RemoveField(
            model_name='musictracks',
            name='saves',
        ),
    ]
